obj-m := fpapf.o fpavf.o rst.o ssopf.o ssowpf.o pki.o pkopf.o lbk.o timpf.o octeontx.o


fpapf-y := fpapf_main.o
fpavf-y := fpavf_main.o
rst-y := rst_main.o
ssopf-y := ssopf_main.o octeontx_mbox.o
ssowpf-y := ssowpf_main.o
pkopf-y := pkopf_main.o
octeontx-y := octeontx_main.o bgx.o
lbk-y := lbk_main.o
timpf-y := timpf_main.o
pki-y := pki_main.o pki_ucode.o pki_config.o
